version: "3.4"
services:
  app:
    container_name: app
    image: d3ibys/php81-fpm-alpine
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - redis
      - mongodb

  nginx:
    container_name: nginx
    image: d3ibys/nginx-1.20.0
    command: nginx -g "daemon off;"
    links:
      - app
    ports:
      - "83:80"
    volumes:
      - ./src:/var/www/html
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - redis
      - mongodb

  schedule:
    image: d3ibys/php81-fpm-alpine
    container_name: app-schedule
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        chmod +x schedule.sh
        /var/www/schedule.sh
    environment:
      - OPCACHE_SAVE_COMMENTS=0
      - OPCACHE_VALIDATE_TIMESTAMPS=0
      - OPCACHE_REVALIDATE_FREQ=0
    volumes:
      - ./src:/var/www
    depends_on:
      - mongodb
      - redis

  queue:
    image: d3ibys/php81-fpm-alpine
    container_name: app-queue
    restart: always
    command: php artisan horizon
    environment:
      - OPCACHE_SAVE_COMMENTS=0
      - OPCACHE_VALIDATE_TIMESTAMPS=0
      - OPCACHE_REVALIDATE_FREQ=0
    volumes:
      - ./src:/var/www
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:7.0.2-alpine
    container_name: redis
    restart: always
    volumes:
      - ./database/redis:/data

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./database/mongodb/db:/data/db
      
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongodb:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"